name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Run oneline script
        run: echo "Hello, World!"

      - name: Run multiline script
        env :
          EXAMPLE_VAR: ${{ secrets.SERVER_API_KEY }}
        run: |
          echo "This is a multiline script."
          echo "It can run multiple commands."
          echo  ${{ env.EXAMPLE_VAR }}